# Default application configuration.

replicaCount: 1

image:
  repository: sahud12/hello-java
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: dockerhub-secret

service:
  type: NodePort
  port: 8080
  nodePort: 30080

container:
  port: 8080
